SET SERVEROUTPUT ON;
/*
DECLARE
v_ename EMP.ENAME%TYPE;
v_sal EMP.SAL%TYPE;
BEGIN
pro_param_out(7788, v_ename, v_sal);
DBMS_OUTPUT.PUT_LINE('ENAME : ' || v_ename);
DBMS_OUTPUT.PUT_LINE('SAL : ' || v_sal);
END;
/

EXECUTE pro_param_out;

*/

/*
--새 테이블 생성--
CREATE TABLE EMP_TRG
(
EMPNO NUMBER(4),
ENAME VARCHAR2(20),
JOB VARCHAR2(10),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER
);

COMMIT;
*/
/*자료입력
INSERT INTO EMP_TRG
VALUES(9999, 'TOMAS', 'ANALYSIS', 7788, TO_DATE('2020-03-03','YYYY-MM-DD'), 1200,
NULL, 20);

INSERT INTO EMP_TRG
VALUES(7788, 'RYAN', 'MANAGER', 1010, TO_DATE('2018-05-03','YYYY-MM-DD'), 2500,
NULL, 20);

SELECT * FROM EMP_TRG;
*/
/*
--트리거 생성--
CREATE OR REPLACE TRIGGER trg_emp_nodml_weekend
BEFORE
INSERT OR UPDATE OR DELETE ON EMP_TRG
BEGIN
IF TO_CHAR(sysdate, 'DY') IN ('월', '화') THEN
IF INSERTING THEN
raise_application_error(-20000, '주말 사원정보 추가 불가');
ELSIF UPDATING THEN
raise_application_error(-20001, '주말 사원정보 수정 불가');
ELSIF DELETING THEN
raise_application_error(-20002, '주말 사원정보 삭제 불가');
ELSE
raise_application_error(-20003, '주말 사원정보 변경 불가');
END IF;
END IF;
END;
/
--오류 발생
UPDATE EMP_TRG SET SAL=3500 WHERE EMPNO=7788;
*/
/*
--트리거 로그테이블 만들기--

CREATE TABLE EMP_TRG_LOG(
TABLENAME VARCHAR2(10), --DML이 수행된 테이블 이름
DML_TYPE VARCHAR(10), --DML명령어 종류
EMPNO NUMBER(4), 
USER_NAME VARCHAR2(20), --DML을 수행한 USER 이름
CHANGE_DATE DATE --DML이 수행된 날짜
);

--트리거 생성 --
CREATE TRIGGER TGR_EMP_LOG
AFTER
INSERT OR UPDATE OR DELETE ON EMP_TRG
FOR EACH ROW

BEGIN

IF INSERTING THEN
    INSERT INTO EMP_TRG_LOG
    VALUES('EMP_TRG', 'INSERT', :NEW.EMPNO, SYS_CONTEXT('USERENV', 'SESSION_USER'),
    sysdate);
    ELSIF UPDATING THEN
    INSERT INTO EMP_TRG_LOG
    VALUES('EMP_TRG', 'UPDATE', :OLD.EMPNO, SYS_CONTEXT('USERENV',
    'SESSION_USER'), sysdate);
    ELSIF DELETING THEN
    INSERT INTO EMP_TRG_LOG
    VALUES('EMP_TRG', 'DELETE', :OLD.EMPNO, SYS_CONTEXT('USERENV', 'SISSON_USER'),
    sysdate);
    END IF;
    END;
*/
/*
INSERT INTO EMP_TRG
VALUES(9998, 'TEST_NAME', 'BELL', 7788, TO_DATE('2026-04-27','YYYY-MM-DD'), 1200,
NULL,20);
COMMIT;

SELECT * FROM EMP_TRG;
*/
/*
UPDATE EMP_TRG
SET SAL = 1300
WHERE MGR=7788;
*/
SELECT TRIGGER_NAME, TRIGGER_TYPE, TRIGGERING_EVENT, TABLE_NAME, STATUS
FROM USER_TRIGGERS;

COMMIT;