--테이블 생성
CREATE TABLE EMP_DDL(
EMPNO      NUMBER(4),
ENAME      VARCHAR2(10),
JOB 
       VARCHAR2(9),
MGR        NUMBER(4),
HIREDATE   DATE,
SAL        NUMBER(7,2),
COMM 
      NUMBER(7,2),
DEPTNO     NUMBER(2)
);
DESC EMP_DDL;

SELECT * FROM EMP_DDL;

--테이블에 생성(EMP_DDL의 모든 필드를 가져와서 EMP_ALTER 테이블을 만들어라)
CREATE TABLE EMP_ALTER AS SELECT * FROM EMP_DDL; 
SELECT * FROM EMP_ALTER;

--테이블에 열추가
ALTER TABLE EMP_ALTER ADD HP VARCHAR2(20);
SELECT * FROM EMP_ALTER;

DESC EMP_ALTER;

--테이블 열의 자료형 변경

ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);
DESC EMP_ALTER;

--인덱스 생성(기준이 되는 튜플이 있으면 보통은 인덱스가 자동으로 만들어진다. )
CREATE INDEX IDX_EMP_SAL
ON EMP(SAL);
SELECT * FROM USER_IND_COLUMNS;

--뷰 생성
GRANT CREATE VIEW TO SYSTEM;

CREATE VIEW VW_EMP /*권한부여*/
AS(SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO=20);

SELECT * FROM VW_EMP;

--제약조건NOT NULL--
--테이블생성--
CREATE TABLE TABLE_NOTNULL(
LOGIN_ID VARCHAR2(20) NOT NULL,
LOGIN_PWD VARCHAR(20) NOT NULL,
TEL VARCHAR(20));

DESC TABLE_NOTNULL;
--정보입력(잘못된예)--
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD, TEL)
VALUES('TEST_ID_01',NULL,'010-1234-5678');
--정보입력(옳바른 예)--
INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD)
VALUES('TEST_ID_01','1324');

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS; /*제약조건 확인 코드(모든 테이블)*/

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL2';/*제약조건 확인 코드(특정 테이블)*/

SELECT * FROM TABLE_NOTNULL;

--제약 조건명 지정하여 테이블 생성--
CREATE TABLE TABLE_NOTNULL2(
LOGIN_ID VARCHAR2(20) CONSTRAINT TBNN2_LGNID_NN NOT NULL,
LOGIN_PWD VARCHAR2(20) CONSTRAINT TBNN2_LGNPW_NN NOT NULL,
TEL VARCHAR2(20));

--제약조건 UNIQUE--
CREATE TABLE TABLE_UNIQUE(
LOGIN_ID VARCHAR2(20) UNIQUE,
LOGIN_PW VARCHAR2(20) NOT NULL,
TEL VARCHAR2(20));

DESC TABLE_UNIQUE;

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_UNIQUE';

INSERT INTO TABLE_UNIQUE(LOGIN_ID, LOGIN_PW, TEL)
VALUES('TEST_01','PWD01','010-1234-5678');

SELECT * FROM TABLE_UNIQUE;

--제약조건 변경--
ALTER TABLE TABLE_UNIQUE
MODIFY(TEL UNIQUE);

UPDATE TABLE_UNIQUE
SET TEL = NULL; /*UNIQUE라 NULL이 들어갈 수 있다.*/

--제약조건 PRIMARY KEY & CHECK & DEFAULT--
CREATE TABLE TABLE_PK(
/*ID는 유일성과 NOT NULL이 필요하므로 PRIMARY KEY를 사용*/
LOGIN_ID VARCHAR(20) PRIMARY KEY,
/*4자 이상 입력만 가능*/
LOGIN_PW VARCHAR(20) CHECK(LENGTH(LOGIN_PW)>3), 
/*TEL에 저장 값 없을때 자동으로 010- 이 저장됨*/
TEL VARCHAR2(20) DEFAULT '010-');

INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PW, TEL)
VALUES('ID01','PW001','010-1131');

SELECT * FROM TABLE_PK;

--제약 조건 FOREIGN KEY--
--부모 테이블 만들고 자식 테이블을 만들어야 한다. 자료 입력도 부모 먼저!!--
--부모 테이블--
CREATE TABLE DEPT_FK(
DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
DNAEM VARCHAR2(14),
LOC VARCHAR2(13));

DESC DEPT_FK;

--자식 테이블 --
CREATE TABLE EMP_FK(
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGE NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK
REFERENCES DEPT_FK(DEPTNO)
);

DESC EMP_FK;

--자료입력(부모테이블)--
INSERT INTO DEPT_FK
VALUES(10, 'TEST_DNAME', 'TEST_LOC');

SELECT * FROM DEPT_FK;

--자료입력(자식 테이블)--
INSERT INTO EMP_FK
VALUES(9999, 'TEST_MNAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01', 'YYYY/MM/DD'),
3000, NULL, 10);

SELECT * FROM EMP_FK;