-- TBL_MEMBER 테이블 생성--
CREATE TABLE TBL_MEMBER(
ID VARCHAR2(20) PRIMARY KEY,
PW VARCHAR2(20) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE
);

COMMIT;
-- TBL_EXIT_MEMBER 테이블 생성--
CREATE TABLE TBL_EXIT_MEMBER(
EXIT_ID VARCHAR2(20),
NAME VARCHAR2(30),
EXIT_DATE DATE DEFAULT SYSDATE
);

-- 기초 데이터 입력 --
INSERT INTO TBL_MEMBER(ID, PW, NAME, REG_DATE)
VALUES('ADMIN', 'ADMIN1234', '관리자', SYSDATE);

-- 트리거 생성 --
CREATE TRIGGER TBL_MEMBER_EXIT
AFTER
DELETE ON TBL_MEMBER FOR EACH ROW

BEGIN
IF DELETING THEN
INSERT INTO TBL_EXIT_MEMBER
VALUES(:OLD.ID, :OLD.NAME, SYSDATE);
END IF;
END;

COMMIT;

delete from tbl_exit_member;